### ISSUE TITLE
如何添加自定义 module.rules ? ERR! [Config File] Config key 'module' is not supported

### ISSUE THREAD

**Issue by 946629031** [ice-lab/build-scripts#96]
ERR! [Config File] Config key 'module' is not supported

my build.json
```
{
  "entry": {
    "preview": "./src/preview.tsx",
    "app": "./src/index.js"
  },
  "vendor": false,
  "devServer": {
    "hot": false
  },
  "publicPath": "/",
  "externals": {
    "react": "var window.React",
    "react-dom": "var window.ReactDOM",
    "prop-types": "var window.PropTypes",
    "@alifd/next": "var window.Next",
    "@alilc/lowcode-engine": "var window.AliLowCodeEngine",
    "@alilc/lowcode-editor-core": "var window.AliLowCodeEngine.common.editorCabin",
    "@alilc/lowcode-editor-skeleton": "var window.AliLowCodeEngine.common.skeletonCabin",
    "@alilc/lowcode-designer": "var window.AliLowCodeEngine.common.designerCabin",
    "@alilc/lowcode-engine-ext": "var window.AliLowCodeEngineExt",
    "@ali/lowcode-engine": "var window.AliLowCodeEngine",
    "moment": "var window.moment",
    "lodash": "var window._"
  },
  "plugins": [
    [
      "build-plugin-react-app"
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "./build.plugin.js"
  ],
  "module": {
    "rules": [
      {
        "use": "babel-loader"
      },
    ]
  }
}
```

then when i run "npm run start "

```sh
> @alilc/lowcode-demo@1.0.9 start /Users/limi/Downloads/lowcode-demo
> build-scripts start --disable-reload --port 5556

@alib/build-scripts 0.1.32
ERR! CONFIG Failed to get config.
ERR! [Config File] Config key 'module' is not supported
Error: [Config File] Config key 'module' is not supported
    at Context.<anonymous> (/Users/limi/Downloads/lowcode-demo/node_modules/@alib/build-scripts/lib/core/Context.js:340:31)
    at Generator.next (<anonymous>)
    at /Users/limi/Downloads/lowcode-demo/node_modules/@alib/build-scripts/lib/core/Context.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/limi/Downloads/lowcode-demo/node_modules/@alib/build-scripts/lib/core/Context.js:4:12)
    at Context.runUserConfig (/Users/limi/Downloads/lowcode-demo/node_modules/@alib/build-scripts/lib/core/Context.js:334:36)
    at Context.<anonymous> (/Users/limi/Downloads/lowcode-demo/node_modules/@alib/build-scripts/lib/core/Context.js:406:24)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/limi/Downloads/lowcode-demo/node_modules/@alib/build-scripts/lib/core/Context.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alilc/lowcode-demo@1.0.9 start: `build-scripts start --disable-reload --port 5556`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @alilc/lowcode-demo@1.0.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/limi/.npm/_logs/2022-04-12T02_08_33_543Z-debug.log
```

**Comment by maoxiaoke** [comment]
@946629031 module 配置不支持，可以参考 https://ice.work/docs/plugin/develop/build 或 README 插件开发章节，自定义插件来修改内置 webpack 配置

**Comment by maoxiaoke** [comment]
另，想要 babel-loader 的最初诉求是什么

**Comment by 946629031** [comment]
> 另，想要 babel-loader 的最初诉求是什么

在 阿里的 [LowCode-demo](https://github.com/alibaba/lowcode-demo) 上修改，使其成为 React 的业务系统 (能使用 babel 够转译 React 的语法)

**Comment by FrominXu** [comment]
> build-plugin-react-app 这个插件默认支持 babel 转义 react 语法

我的项目中依赖的一个npm包的js内有可选链操作符，导致编译不过，好像也需要用rule来处理，有什么好的方法吗

**Comment by maoxiaoke** [comment]
@FrominXu 默认不编译 node_modules，如有需要使用 https://ice.work/docs/config/about/#compiledependencies- 这个配置

**Comment by FrominXu** [comment]
> @FrominXu 默认不编译 node_modules，如有需要使用 https://ice.work/docs/config/about/#compiledependencies- 这个配置

我试了，但提示不支持这个参数，应该是我用了 build-plugin-component 这个插件的原因

**Comment by longshao512** [comment]
我想要加loader 有什么好的推荐么
